---
language: python
services: docker
cache:
  pip: true

install:
  - pip install pipenv
  - pipenv install

script:
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
