---
- block:
    - name: Configure enforcing of TLS
      ldap_attr:
        params: "{{ dirsrv_ldap_auth }}"
        dn: "cn=config"
        name: "{{ item.name }}"
        values: "{{ item.value }}"
        state: exact
      with_items:
        - { name: "nsslapd-require-secure-binds", value: "{{ 'on' if dirsrv_tls_enabled and dirsrv_tls_enforced else 'off' }}" }
        - { name: "nsslapd-minssf", value: "{{ dirsrv_tls_minssf if dirsrv_tls_enabled and dirsrv_tls_enforced else '0' }}" }
      failed_when: false
      tags: [ dirsrv_tls ]

  rescue:
    - name: Configure enforcing of TLS, over TLS
      ldap_attr:
        params: "{{ dirsrv_ldap_auth_later }}"
        dn: "cn=config"
        name: "{{ item.name }}"
        values: "{{ item.value }}"
        state: exact
      with_items:
        - { name: "nsslapd-require-secure-binds", value: "{{ 'on' if dirsrv_tls_enabled and dirsrv_tls_enforced else 'off' }}" }
        - { name: "nsslapd-minssf", value: "{{ dirsrv_tls_minssf if dirsrv_tls_enabled and dirsrv_tls_enforced else '0' }}" }
      tags: [ dirsrv_tls ]
...