---
- block:
    - name: Set configuration to enable LDAPI
      set_fact:
        dirsrv_ldapi_config:
          - { name: "nsslapd-ldapilisten", value: "on" }
          - { name: "nsslapd-ldapifilepath", value: "/var/run/slapd-{{ dirsrv_serverid }}.socket" }
          - { name: "nsslapd-ldapiautobind", value: "on" }
          - { name: "nsslapd-ldapimaptoentries", value: "off" }
      when: dirsrv_ldapi_enabled|bool

    - name: Set configuration to disable LDAPI
      set_fact:
        dirsrv_ldapi_config:
          - { name: "nsslapd-ldapilisten", value: "off" }
          - { name: "nsslapd-ldapiautobind", value: "off" }
      when: not dirsrv_ldapi_enabled

    - name: Configure LDAPI
      ldap_attr:
        params: "{{ dirsrv_ldap_auth }}"
        dn: "cn=config"
        name: "{{ item.name }}"
        values: "{{ item.value }}"
        state: exact
      with_items: "{{ dirsrv_ldapi_config }}"
      notify: dirsrv restart

  rescue:
    - name: Configure LDAPI over LDAPI
      ldap_attr:
        server_uri: "ldapi:///var/run/slapd-{{ dirsrv_serverid }}.socket"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        name: "{{ item.name }}"
        values: "{{ item.value }}"
        state: exact
      with_items: "{{ dirsrv_ldapi_config }}"
      notify: dirsrv restart

# Documentation: https://directory.fedoraproject.org/docs/389ds/design/sasl-mechanism-configuration.html
# TODO: "none" means "everything is allowed"... how to allow none (or just EXTERNAL that is always enabled but not always allowed or whatever?)
- block:
    - name: Configure SASL
      ldap_attr:
        params: "{{ dirsrv_ldap_auth }}"
        dn: "cn=config"
        name: "nsslapd-allowed-sasl-mechanisms"
        values: "{{ 'PLAIN' if dirsrv_sasl_plain_enabled else [] }}"
        state: exact
      register: dirsrv_sasl_result

  rescue:
    # Deleting an attribute fails if the the attribute doesn't exist,
    # yay for idempotence...
    - name: Assert that task failed successfully
      assert:
        that:
          - not dirsrv_sasl_result.changed
          - "'desc' in dirsrv_sasl_result.details"
          - "{{ dirsrv_sasl_result.details }}.desc == 'No such attribute'"

- block:
    - name: Configure password storage scheme
      ldap_attr:
        params: "{{ dirsrv_ldap_auth }}"
        dn: "cn=config"
        name: "passwordStorageScheme"
        values: "{{ dirsrv_password_storage_scheme }}"
        state: exact
      register: dirsrv_pwdstorage_result

  rescue:
    # Same as above
    - name: Assert that task failed successfully
      assert:
        that:
          - not dirsrv_pwdstorage_result.changed
          - "'desc' in dirsrv_pwdstorage_result.details"
          - "{{ dirsrv_pwdstorage_result.details }}.desc == 'No such attribute'"
...