---
- name: Converge
  hosts: all
  roles:
    -
      role: 389ds-server
      dirsrv_suffix: "dc=test,dc=local"
      dirsrv_serverid: test
      dirsrv_rootdn_password: secret
      dirsrv_listen_host: 0.0.0.0
      dirsrv_tls_enabled: true
      dirsrv_tls_cert_file: tls_test_local_cert.pem
      dirsrv_tls_key_file: tls_test_local.key
      dirsrv_tls_files_remote: false
      dirsrv_tls_certificate_trusted: false
